'use strict';
const C=MessageCore,$=id=>document.getElementById(id);
let root=C.node('order','object',{children:[C.node('number','string',{len:20,required:true,value:'ORD-001'}),C.node('amount','number',{digits:15,scale:2,required:true,value:'1250.50',description:'Сумма заказа'}),C.node('active','boolean',{required:true,value:'true'}),C.node('items','array',{children:[C.node('item','object',{children:[C.node('sku','string',{len:50,value:'SKU-001',required:true})]})]})]}),selected=root.children[1].id,mode='json',tab='message',namespace='',texts={json:{message:C.json(root),schema:''},xml:{message:'',schema:''}},filePurpose='project',appSection='builder',diagramKind='component',integration={sender:'1С:ERP',senderInterface:'REST API 1С:ERP',receiver:'CRM',payload:'Заказ клиента',format:'JSON',method:'Kafka topic',interaction:'Асинхронный',useBroker:true,broker:'Kafka',useReturn:true,returnInterface:'REST API CRM',responsePayload:'Результат обработки',responseFormat:'JSON',returnMethod:'HTTP REST',returnReceiver:'1С:ERP'};
const labels={object:'Объект',array:'Массив',string:'Строка',number:'Число',integer:'Целое',boolean:'Булево',date:'Дата',dateTime:'Дата и время',null:'null'};
let excelBook=null,excelRows=[],excelMapped=[];
const exactTranslations={
 'номер заказа':'order_number','дата заказа':'order_date','сумма заказа':'order_amount','код товара':'product_code','наименование товара':'product_name','количество товара':'product_quantity','идентификатор клиента':'customer_id','номер документа':'document_number','дата документа':'document_date','сумма документа':'document_amount'
};
const wordTranslations={номер:'number',код:'code',наименование:'name',название:'name',имя:'name',описание:'description',дата:'date',время:'time',сумма:'amount',количество:'quantity',цена:'price',валюта:'currency',клиент:'customer',покупатель:'customer',контрагент:'counterparty',заказ:'order',товар:'product',услуга:'service',организация:'company',документ:'document',статус:'status',признак:'flag',адрес:'address',телефон:'phone',почта:'email',склад:'warehouse',единица:'unit',артикул:'sku',ставка:'rate',скидка:'discount',налог:'tax',ндс:'vat',комментарий:'comment',идентификатор:'id',ссылка:'reference',внешний:'external',внутренний:'internal',договор:'contract',проект:'project',сотрудник:'employee',подразделение:'department',регион:'region',страна:'country',город:'city',индекс:'postal_code',неизвестное:'unknown',поле:'field'};
const translitMap={а:'a',б:'b',в:'v',г:'g',д:'d',е:'e',ё:'e',ж:'zh',з:'z',и:'i',й:'y',к:'k',л:'l',м:'m',н:'n',о:'o',п:'p',р:'r',с:'s',т:'t',у:'u',ф:'f',х:'kh',ц:'ts',ч:'ch',ш:'sh',щ:'sch',ъ:'',ы:'y',ь:'',э:'e',ю:'yu',я:'ya'};
for(const t of C.types){const o=document.createElement('option');o.value=t;o.textContent=labels[t]+' · '+t;$('type').append(o);}
function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
function safe(fn){return (...args)=>{try{fn(...args);}catch(e){status(e.message,true);}};}
function renderRows(){const body=$('rows');body.replaceChildren();function row(n,depth){const tr=document.createElement('tr');tr.className=n.id===selected?'selected':'';tr.tabIndex=0;tr.setAttribute('aria-label',n.name+' '+n.type);const name=document.createElement('td');name.style.paddingLeft=(12+depth*19)+'px';name.title=n.source||n.name;const icon=document.createElement('span');icon.className='tree-icon';icon.textContent={object:'{}',array:'[]',number:'123',integer:'123',boolean:'✓',string:'abc',null:'∅',date:'◷',dateTime:'◷'}[n.type];name.append(icon,document.createTextNode((n.xmlAttribute?'@':'')+n.name));tr.append(name);for(const v of [n.type,n.len,n.digits,n.scale]){const td=document.createElement('td');td.textContent=v===''?'—':v;tr.append(td);}const td=document.createElement('td'),checkbox=document.createElement('input');checkbox.type='checkbox';checkbox.checked=n.required;checkbox.setAttribute('aria-label',n.name+': обязательное');checkbox.addEventListener('click',e=>e.stopPropagation());checkbox.addEventListener('change',()=>{n.required=checkbox.checked;if(selected===n.id)$('required').checked=n.required;status('Параметры изменены. Нажмите «Создать…» для обновления текста.');});td.append(checkbox);tr.append(td);tr.addEventListener('click',()=>{selected=n.id;render();});tr.addEventListener('keydown',e=>{if(e.key==='Enter'){selected=n.id;render();}});body.append(tr);n.children.forEach(c=>row(c,depth+1));}row(root,0);}
function inspector(){const n=C.find(root,selected)||root;selected=n.id;for(const k of ['name','type','value','description','source','len','digits','scale'])$(k).value=n[k];for(const k of ['required','xmlAttribute'])$(k).checked=n[k];$('len').disabled=!['string','date','dateTime'].includes(n.type);$('digits').disabled=!['number','integer'].includes(n.type);$('scale').disabled=n.type!=='number';$('value').disabled=['object','array','null'].includes(n.type);$('child').disabled=!['object','array'].includes(n.type);$('delete').disabled=n===root;$('xmlAttribute').disabled=n===root||['object','array','null'].includes(n.type);}
function render(){renderRows();inspector();document.querySelectorAll('.xml-only').forEach(x=>x.hidden=mode!=='xml');$('jsonMode').classList.toggle('active',appSection==='builder'&&mode==='json');$('xmlMode').classList.toggle('active',appSection==='builder'&&mode==='xml');$('umlMode').classList.toggle('active',appSection==='uml');$('builderView').hidden=appSection==='uml';$('umlView').hidden=appSection!=='uml';$('messageActions').hidden=appSection==='uml';$('generate').textContent='Создать '+mode.toUpperCase();$('messageTab').classList.toggle('selected',tab==='message');$('schemaTab').classList.toggle('selected',tab==='schema');$('formatLabel').textContent=tab==='schema'?(mode==='json'?'JSON Schema 2020-12':'XSD 1.0'):mode.toUpperCase();$('namespace').value=namespace;if(appSection==='uml')renderUML();}
function lines(){const count=$('code').value.split('\n').length;$('lines').textContent=Array.from({length:count},(_,i)=>i+1).join('\n');$('lines').scrollTop=$('code').scrollTop;}
function showText(){ $('code').value=texts[mode][tab];lines();render();}
function keep(){texts[mode][tab]=$('code').value;}
function switchTab(t){keep();tab=t;showText();}
function switchMode(m){keep();appSection='builder';mode=m;showText();status('Выбран '+m.toUpperCase()+'. Структура сохранена.');}
function loadIntegrationForm(){$('senderSystem').value=integration.sender;$('senderInterface').value=integration.senderInterface;$('receiverSystem').value=integration.receiver;$('payloadName').value=integration.payload;$('payloadFormat').value=integration.format;$('transferMethod').value=integration.method;$('interactionMode').value=integration.interaction;$('useBroker').checked=integration.useBroker;$('brokerSystem').value=integration.broker;$('useReturn').checked=integration.useReturn;$('returnInterface').value=integration.returnInterface;$('responsePayload').value=integration.responsePayload;$('responseFormat').value=integration.responseFormat;$('returnMethod').value=integration.returnMethod;$('returnReceiver').value=integration.returnReceiver;}
function readIntegrationForm(){integration={sender:$('senderSystem').value.trim()||'Отправитель',senderInterface:$('senderInterface').value.trim()||'Интерфейс отправителя',receiver:$('receiverSystem').value.trim()||'Получатель',payload:$('payloadName').value.trim()||'Данные запроса',format:$('payloadFormat').value,method:$('transferMethod').value,interaction:$('interactionMode').value,useBroker:$('useBroker').checked,broker:$('brokerSystem').value.trim()||'Брокер',useReturn:$('useReturn').checked,returnInterface:$('returnInterface').value.trim()||'Интерфейс ответа',responsePayload:$('responsePayload').value.trim()||'Результат обработки',responseFormat:$('responseFormat').value,returnMethod:$('returnMethod').value,returnReceiver:$('returnReceiver').value.trim()||integration.sender||'Получатель ответа'};}
function englishFieldName(value,style='snake'){
 const normalized=String(value??'').trim().toLowerCase().replace(/ё/g,'е').replace(/[()\[\]{}]/g,' ').replace(/[^a-zа-я0-9]+/gi,' ').trim();
 let translated=exactTranslations[normalized]||normalized.split(/\s+/).filter(Boolean).map(word=>wordTranslations[word]||[...word].map(ch=>translitMap[ch]??ch).join('')).join('_');
 let parts=translated.replace(/([a-z0-9])([A-Z])/g,'$1_$2').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'').split('_').filter(Boolean);
 if(!parts.length)parts=['field'];return style==='snakeCaps'?parts.map(p=>p[0].toUpperCase()+p.slice(1)).join('_'):parts.join('_');
}
function excelType(value){const raw=String(value??'').trim(),base=raw.replace(/\s*\([^)]*\)\s*$/,'').trim().toLowerCase().replace(/ё/g,'е');let type='string',warning='';if(/^(строка|string|text|varchar|char)$/.test(base))type='string';else if(/^(число|number|decimal|numeric|float|double)$/.test(base))type='number';else if(/^(целое|integer|int|long)$/.test(base))type='integer';else if(/^(булево|boolean|bool|логический)$/.test(base))type='boolean';else if(/^(дата.?время|datetime|date.?time|timestamp)$/.test(base))type='dateTime';else if(/^(дата|date)$/.test(base))type='date';else if(/^(объект|object)$/.test(base))type='object';else if(/^(массив|array)$/.test(base))type='array';else if(base)warning='Неизвестный тип «'+raw+'»: использована строка';return {type,warning,inlineSize:(raw.match(/\(([^)]+)\)/)||[])[1]||''};}
function excelSize(value,type,inlineSize=''){const text=String(value??'').trim()||inlineSize;if(!text)return {len:'',digits:'',scale:'',warning:'',valid:true};const match=text.replace(/\s/g,'').match(/^(\d+)(?:[,.xх\/]([0-9]+))?$/i);if(!match)return {len:'',digits:'',scale:'',warning:'Неверный формат длины «'+text+'»',valid:false};const first=+match[1],second=match[2]===undefined?'':+match[2];if(first<1)return {len:'',digits:'',scale:'',warning:'Длина должна быть больше нуля',valid:false};if(['number','integer'].includes(type)){if(first>15)return {len:'',digits:'',scale:'',warning:'Поддерживается не более 15 цифр',valid:false};if(type==='integer'&&second!=='')return {len:'',digits:'',scale:'',warning:'Для целого числа точность после запятой не задаётся',valid:false};if(second!==''&&second>first)return {len:'',digits:'',scale:'',warning:'Точность больше общей разрядности',valid:false};return {len:'',digits:first,scale:second,warning:'',valid:true};}if(type==='string')return second===''?{len:first,digits:'',scale:'',warning:'',valid:true}:{len:'',digits:'',scale:'',warning:'Для строки укажите одно число',valid:false};return {len:'',digits:'',scale:'',warning:'Размер не применяется к типу '+labels[type],valid:true};}
function excelStatus(message,error=false){$('excelStatus').textContent=message;$('excelStatus').classList.toggle('error',error);}
function fillColumnSelect(select,headers,optional=false){select.replaceChildren();if(optional){const empty=document.createElement('option');empty.value='-1';empty.textContent='Не использовать';select.append(empty);}headers.forEach((header,index)=>{const option=document.createElement('option');option.value=String(index);option.textContent=header||'Колонка '+(index+1);select.append(option);});select.disabled=false;}
function detectColumn(headers,pattern,fallback=-1){const index=headers.findIndex(value=>pattern.test(String(value).toLowerCase()));return index<0?fallback:index;}
function buildExcelPreview(){const body=$('excelPreviewRows');body.replaceChildren();if(!excelRows.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.textContent='На выбранном листе нет данных.';tr.append(td);body.append(tr);excelMapped=[];$('excelImport').disabled=true;excelStatus('Нет строк для импорта',true);return;}const nameIndex=+$('excelNameColumn').value,typeIndex=+$('excelTypeColumn').value,sizeIndex=+$('excelSizeColumn').value,style=$('excelNameStyle').value,used=new Map();excelMapped=excelRows.slice(1).filter(row=>String(row[nameIndex]??'').trim()).slice(0,5000).map(row=>{const source=String(row[nameIndex]??'').trim(),typeInfo=excelType(typeIndex<0?'':row[typeIndex]),sizeInfo=excelSize(sizeIndex<0?'':row[sizeIndex],typeInfo.type,typeInfo.inlineSize);let name=englishFieldName(source,style),count=(used.get(name)||0)+1;used.set(name,count);if(count>1)name+='_'+count;const warnings=[typeInfo.warning,sizeInfo.warning].filter(Boolean);return {source,name,type:typeInfo.type,len:sizeInfo.len,digits:sizeInfo.digits,scale:sizeInfo.scale,warning:warnings.join('. '),valid:sizeInfo.valid};});if(!excelMapped.length){const tr=document.createElement('tr'),td=document.createElement('td');td.colSpan=5;td.textContent='В колонке атрибутов нет заполненных строк.';tr.append(td);body.append(tr);$('excelImport').disabled=true;excelStatus('Выберите другую колонку атрибутов',true);return;}for(const item of excelMapped.slice(0,100)){const tr=document.createElement('tr');for(const value of [item.source,item.name,labels[item.type],item.type==='string'?(item.len||'—'):['number','integer'].includes(item.type)?(item.digits?(item.digits+(item.scale!==''?','+item.scale:'')):'—'):'—']){const td=document.createElement('td');td.textContent=value;tr.append(td);}const result=document.createElement('td');result.textContent=item.warning||'Готово';result.className=item.warning?'warn':'ok';tr.append(result);body.append(tr);}const invalid=excelMapped.filter(x=>!x.valid).length;$('excelImport').disabled=invalid>0;excelStatus(invalid?invalid+' строк требуют исправления в Excel':excelMapped.length+' атрибутов готовы к загрузке',invalid>0);}
function loadExcelSheet(){const name=$('excelSheet').value,sheet=excelBook?.Sheets[name];excelRows=sheet?XLSX.utils.sheet_to_json(sheet,{header:1,defval:'',raw:false,blankrows:false}):[];const width=Math.max(0,...excelRows.map(r=>r.length)),headers=Array.from({length:width},(_,i)=>String(excelRows[0]?.[i]??'').trim()||'Колонка '+(i+1));for(const id of ['excelNameColumn','excelTypeColumn','excelSizeColumn'])fillColumnSelect($(id),headers,id!=='excelNameColumn');$('excelNameColumn').value=String(detectColumn(headers,/наимен|атрибут|имя|field|name/,0));$('excelTypeColumn').value=String(detectColumn(headers,/тип|type/,-1));$('excelSizeColumn').value=String(detectColumn(headers,/длин|разряд|точн|length|precision|size/,-1));buildExcelPreview();}
async function readExcelFile(file){try{if(!file)return;if(file.size>20*1024*1024)throw Error('Максимальный размер Excel-файла — 20 МБ');if(typeof XLSX==='undefined')throw Error('Модуль чтения Excel не загружен');excelBook=XLSX.read(await file.arrayBuffer(),{type:'array'});if(!excelBook.SheetNames.length)throw Error('В книге нет листов');$('excelFileName').textContent=file.name;$('excelSheet').replaceChildren(...excelBook.SheetNames.map(name=>{const option=document.createElement('option');option.value=name;option.textContent=name;return option;}));$('excelSheet').disabled=false;loadExcelSheet();}catch(error){excelBook=null;excelRows=[];excelMapped=[];$('excelImport').disabled=true;excelStatus(error.message,true);}}
function setSvgNodeText(id,value){const element=$(id),words=String(value).trim().split(/\s+/),lines=[];let current='';for(const word of words){if((current+' '+word).trim().length>18&&current){lines.push(current);current=word;}else current=(current+' '+word).trim();}if(current)lines.push(current);if(lines.length>2){lines[1]=lines.slice(1).join(' ');lines.length=2;}if(lines[1]?.length>22)lines[1]=lines[1].slice(0,21)+'…';element.replaceChildren();const x=element.getAttribute('x'),y=+element.getAttribute('y');if(lines.length<2){element.textContent=lines[0]||'';return;}lines.forEach((line,index)=>{const span=document.createElementNS('http://www.w3.org/2000/svg','tspan');span.setAttribute('x',x);span.setAttribute('y',String(y-9+index*19));span.textContent=line;element.append(span);});}
function renderUML(){
 const hide=(id,value)=>$(id).toggleAttribute('hidden',value),attr=(id,name,value)=>$(id).setAttribute(name,value),mobile=window.matchMedia('(max-width: 500px)').matches;
 const nodeValues={componentSender:integration.sender,componentSenderInterface:integration.senderInterface,componentRequestData:integration.payload+' · '+integration.format,componentBroker:integration.broker,componentReceiver:integration.receiver,componentReturnReceiver:integration.returnReceiver,componentResponseData:integration.responsePayload+' · '+integration.responseFormat,componentReturnInterface:integration.returnInterface,componentReturnBroker:integration.broker,componentReturnOrigin:integration.receiver,flowSender:integration.sender,flowSenderInterface:integration.senderInterface,flowRequestData:integration.payload+' · '+integration.format,flowBroker:integration.broker,flowReceiver:integration.receiver,flowReturnReceiver:integration.returnReceiver,flowResponseData:integration.responsePayload+' · '+integration.responseFormat,flowReturnInterface:integration.returnInterface,flowReturnBroker:integration.broker,flowReturnOrigin:integration.receiver};
 for(const [id,value] of Object.entries(nodeValues))setSvgNodeText(id,value);
 const forwardMethod=integration.method+' · '+integration.interaction,returnMethod=integration.returnMethod+' · '+integration.interaction;
 $('componentForwardMethod').textContent=forwardMethod;$('componentReturnMethod').textContent=returnMethod;$('flowForwardMethod').textContent=forwardMethod;$('flowReturnMethod').textContent=returnMethod;
 $('brokerNameLabel').hidden=!integration.useBroker;$('umlView').querySelectorAll('[data-return-field]').forEach(element=>element.hidden=!integration.useReturn);
 for(const prefix of ['component','flow']){hide(prefix+'BrokerGroup',!integration.useBroker);hide(prefix+'ReturnBrokerGroup',!integration.useBroker||!integration.useReturn);hide(prefix+'ReturnRoute',!integration.useReturn);}
 hide('flowReturnLane',!integration.useReturn||mobile);hide('flowForwardLane',mobile);
 const groups=['SenderGroup','SenderInterfaceGroup','RequestDataGroup','BrokerGroup','ReceiverGroup','ReturnBrokerGroup','ReturnInterfaceGroup','ResponseDataGroup','ReturnReceiverGroup','ReturnOriginGroup'];
 if(mobile){
  const forwardY=integration.useBroker?[40,180,320,460,600]:[40,180,320,null,460],returnY=integration.useBroker?[760,900,1040,1180]:[null,620,760,900];
  for(const prefix of ['component','flow']){
   attr(prefix+'Diagram','viewBox','0 0 360 '+(integration.useReturn?(integration.useBroker?1300:1020):(integration.useBroker?720:580)));
   attr(prefix+'Heading','visibility','hidden');
   const baseX=[20,205,390,575,760],baseY=110;
   ['SenderGroup','SenderInterfaceGroup','RequestDataGroup','BrokerGroup','ReceiverGroup'].forEach((suffix,index)=>{if(forwardY[index]!==null)attr(prefix+suffix,'transform','translate('+(110-baseX[index])+' '+(forwardY[index]-baseY)+')');});
   const returnBase={ReturnBrokerGroup:[575,320,returnY[0]],ReturnInterfaceGroup:[390,320,returnY[1]],ResponseDataGroup:[205,320,returnY[2]],ReturnReceiverGroup:[20,320,returnY[3]]};
   for(const [suffix,[x,y,targetY]] of Object.entries(returnBase))if(targetY!==null)attr(prefix+suffix,'transform','translate('+(110-x)+' '+(targetY-y)+')');
   hide(prefix+'ReturnOriginGroup',true);attr(prefix+'ForwardMethod','visibility','hidden');attr(prefix+'ReturnMethod','visibility','hidden');
   attr(prefix+'Forward1','d','M180 124 V180');attr(prefix+'Forward2','d','M180 264 V320');
   if(integration.useBroker){attr(prefix+'Forward3','d','M180 404 V460');hide(prefix+'Forward4',false);attr(prefix+'Forward4','d','M180 544 V600');if(integration.useReturn){attr(prefix+'Return1','d','M180 684 V760');hide(prefix+'Return2',false);attr(prefix+'Return2','d','M180 844 V900');attr(prefix+'Return3','d','M180 984 V1040');attr(prefix+'Return4','d','M180 1124 V1180');}}
   else{attr(prefix+'Forward3','d','M180 404 V460');hide(prefix+'Forward4',true);if(integration.useReturn){attr(prefix+'Return1','d','M180 544 V620');hide(prefix+'Return2',true);attr(prefix+'Return3','d','M180 704 V760');attr(prefix+'Return4','d','M180 844 V900');}}
  }
 }else{
  for(const prefix of ['component','flow']){
   attr(prefix+'Diagram','viewBox','0 0 920 '+(integration.useReturn?500:250));attr(prefix+'Heading','visibility','visible');for(const suffix of groups)attr(prefix+suffix,'transform','');hide(prefix+'ReturnOriginGroup',!integration.useReturn);attr(prefix+'ForwardMethod','visibility','visible');attr(prefix+'ReturnMethod','visibility','visible');
   attr(prefix+'Forward1','d','M160 152 H205');attr(prefix+'Forward2','d','M345 152 H390');
   if(integration.useBroker){attr(prefix+'Forward3','d','M530 152 H575');hide(prefix+'Forward4',false);attr(prefix+'Forward4','d','M715 152 H760');if(integration.useReturn){attr(prefix+'Return1','d','M760 362 H715');hide(prefix+'Return2',false);attr(prefix+'Return2','d','M575 362 H530');}}
   else{attr(prefix+'Forward3','d','M530 152 H760');hide(prefix+'Forward4',true);if(integration.useReturn){attr(prefix+'Return1','d','M760 362 H530');hide(prefix+'Return2',true);}}
   attr(prefix+'Return3','d','M390 362 H345');attr(prefix+'Return4','d','M205 362 H160');
  }
 }
 hide('componentDiagram',diagramKind!=='component');hide('flowDiagram',diagramKind!=='flow');$('componentDiagramTab').classList.toggle('selected',diagramKind==='component');$('flowDiagramTab').classList.toggle('selected',diagramKind==='flow');$('componentDiagramTab').setAttribute('aria-pressed',diagramKind==='component');$('flowDiagramTab').setAttribute('aria-pressed',diagramKind==='flow');
}
function plantUML(){const q=s=>'"'+String(s).replace(/["\n\r]/g,' ')+'"',forward=integration.payload+'\\n'+integration.format+'\\n'+integration.method+' · '+integration.interaction,back=integration.responsePayload+'\\n'+integration.responseFormat+'\\n'+integration.returnMethod+' · '+integration.interaction,lines=['@startuml','left to right direction','title '+(diagramKind==='component'?'Диаграмма компонентов интеграционного взаимодействия':'Схема интеграционного взаимодействия и потоков данных'),'component '+q(integration.sender)+' as Sender','interface '+q(integration.senderInterface)+' as SenderApi','artifact '+q(integration.payload)+' as Request','component '+q(integration.receiver)+' as Receiver','Sender --> SenderApi','SenderApi --> Request : '+integration.format];if(integration.useBroker){lines.push('queue '+q(integration.broker)+' as Broker','Request --> Broker : '+forward,'Broker --> Receiver : '+forward);}else lines.push('Request --> Receiver : '+forward);if(integration.useReturn){lines.push('interface '+q(integration.returnInterface)+' as ReturnApi','artifact '+q(integration.responsePayload)+' as Response','component '+q(integration.returnReceiver)+' as ReturnReceiver');if(integration.useBroker)lines.push('Receiver --> Broker : '+back,'Broker --> ReturnApi : '+back);else lines.push('Receiver --> ReturnApi : '+back);lines.push('ReturnApi --> Response : '+integration.responseFormat,'Response --> ReturnReceiver : '+back);}lines.push('@enduml');return lines.join('\n');}
for(const k of ['name','type','value','description','source','len','digits','scale','required','xmlAttribute'])$(k).addEventListener('change',safe(()=>{const n=C.find(root,selected);if(k==='type'&&n.children.length&&!['object','array'].includes($(k).value)){inspector();throw Error('Сначала удалите вложенные поля или оставьте тип «Объект / Массив».');}n[k]=['required','xmlAttribute'].includes(k)?$(k).checked:$(k).value;if(k==='type'){n.xmlAttribute=false;if(n.type==='boolean')n.value='false';if(['number','integer'].includes(n.type))n.value='0';if(n.type==='integer')n.scale='';if(!['number','integer'].includes(n.type)){n.digits='';n.scale='';}if(n.type!=='string')n.len='';if(n.type==='date')n.value='2026-01-01';if(n.type==='dateTime')n.value='2026-01-01T00:00:00Z';}render();status('Параметры изменены. Нажмите «Создать…» для обновления текста.');}));
$('namespace').addEventListener('change',()=>namespace=$('namespace').value);
// Keep edits immediately; generation must also see a value entered before focus leaves the field.
for(const k of ['name','value','description','source','len','digits','scale'])$(k).addEventListener('input',()=>{const n=C.find(root,selected);n[k]=$(k).value;renderRows();status('Параметры изменены. Нажмите «Создать…» для обновления текста.');});
$('namespace').addEventListener('input',()=>namespace=$('namespace').value);
$('code').addEventListener('input',()=>{keep();lines();});$('code').addEventListener('scroll',()=>$('lines').scrollTop=$('code').scrollTop);
$('jsonMode').onclick=()=>switchMode('json');$('xmlMode').onclick=()=>switchMode('xml');$('umlMode').onclick=()=>{keep();appSection='uml';render();status('Параметры UML-диаграммы готовы к редактированию.');};$('messageTab').onclick=()=>switchTab('message');$('schemaTab').onclick=()=>switchTab('schema');
$('excelOpen').onclick=()=>{$('excelDialog').showModal();excelStatus(excelBook?'Настройте соответствие колонок':'Выберите Excel-файл');};$('excelChoose').onclick=()=>{$('excelFile').value='';$('excelFile').click();};$('excelClose').onclick=$('excelCancel').onclick=()=>$('excelDialog').close();$('excelFile').onchange=()=>readExcelFile($('excelFile').files[0]);$('excelSheet').onchange=loadExcelSheet;for(const id of ['excelNameColumn','excelTypeColumn','excelSizeColumn','excelNameStyle'])$(id).onchange=buildExcelPreview;$('excelImport').onclick=safe(()=>{if(!excelMapped.length||excelMapped.some(x=>!x.valid))throw Error('Сначала исправьте параметры импорта');root.type='object';root.children=excelMapped.map(item=>C.node(item.name,item.type,{len:item.len,digits:item.digits,scale:item.scale,source:item.source,value:item.type==='boolean'?'false':['number','integer'].includes(item.type)?'0':item.type==='date'?'2026-01-01':item.type==='dateTime'?'2026-01-01T00:00:00Z':''}));selected=root.children[0]?.id||root.id;appSection='builder';$('excelDialog').close();render();status(excelMapped.length+' атрибутов загружено из Excel. Нажмите «Создать '+mode.toUpperCase()+'».');});
$('componentDiagramTab').onclick=()=>{diagramKind='component';renderUML();};$('flowDiagramTab').onclick=()=>{diagramKind='flow';renderUML();};
for(const id of ['senderSystem','senderInterface','receiverSystem','payloadName','payloadFormat','transferMethod','interactionMode','useBroker','brokerSystem','useReturn','returnInterface','responsePayload','responseFormat','returnMethod','returnReceiver'])for(const eventName of ['input','change'])$(id).addEventListener(eventName,()=>{readIntegrationForm();renderUML();status('Диаграмма обновлена.');});
$('plantUmlExport').onclick=()=>{const text=plantUML();if(typeof showExport==='function')showExport('PlantUML · текст для копирования',text,false);else if(typeof download==='function')download(text,'integration.puml','text/plain');};
function add(nested){const n=C.find(root,selected),p=nested?n:C.parent(root,selected)||root;if(!['object','array'].includes(p.type))throw Error('Выберите объект или массив');let name=p.type==='array'?'item':'field';let i=1;while(p.type!=='array'&&p.children.some(c=>c.name===name))name='field'+i++;const next=p.type==='array'&&p.children.length?C.clone(p.children[0]):C.node(name);p.children.push(next);selected=next.id;render();status('Поле добавлено');}
$('add').onclick=safe(()=>add(false));$('child').onclick=safe(()=>add(true));$('delete').onclick=safe(()=>{const p=C.parent(root,selected);if(!p)return;p.children=p.children.filter(c=>c.id!==selected);selected=p.id;render();status('Поле удалено');});
$('generate').onclick=safe(()=>{keep();texts[mode].message=mode==='json'?C.json(root):C.xml(root,namespace);tab='message';showText();status('Сообщение создано');});
$('schema').onclick=safe(()=>{keep();texts[mode].schema=mode==='json'?C.schema(root):C.xsd(root,namespace);tab='schema';showText();status('Схема создана');});
$('import').onclick=safe(()=>{keep();const text=$('code').value.trim();if(!text)throw Error('Вставьте текст или откройте файл справа');let next;if(mode==='json'){const parsed=C.parseJSON(text);next=tab==='schema'?C.fromSchema(parsed,parsed.title||'root'):C.infer(parsed,root.name);}else{const result=tab==='schema'?C.fromXSD(text):C.fromXML(text);next=result.root;namespace=result.namespace;}root=next;selected=root.id;render();status(tab==='schema'?'Структура и поддерживаемые ограничения загружены':'Структура и значения загружены. Обязательность, длину и разрядность задайте по договорённости обмена.');});
function download(text,name,type){const a=document.createElement('a'),u=URL.createObjectURL(new Blob([text],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
$('download').onclick=safe(()=>download($('code').value,(root.name.replace(/[^\p{L}\p{N}_-]/gu,'_')||'message')+(tab==='schema'?(mode==='json'?'.schema.json':'.xsd'):'.'+mode),mode==='json'?'application/json':'application/xml'));
$('save').onclick=safe(()=>{keep();readIntegrationForm();download(JSON.stringify({version:1,root,namespace,mode,texts,integration,diagramKind,appSection},null,2),'message-project.json','application/json');status('Проект сохранён');});
$('copy').onclick=async()=>{try{await navigator.clipboard.writeText($('code').value);status('Текст скопирован');}catch{$('code').focus();$('code').select();status('Нажмите Ctrl+C, чтобы скопировать выделенный текст');}};
function openFile(purpose){filePurpose=purpose;$('file').accept=purpose==='project'?'.json':'.json,.xml,.xsd,.txt';$('file').value='';$('file').click();}
$('open').onclick=()=>openFile('project');$('loadText').onclick=()=>openFile('text');
$('file').onchange=async()=>{const f=$('file').files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('Максимальный размер файла — 5 МБ');const text=(await f.text()).replace(/^\uFEFF/,'');if(filePurpose==='project'){const p=C.restore(JSON.parse(text));root=p.root;namespace=p.namespace||'';mode=p.mode==='xml'?'xml':'json';texts=p.texts||{json:{message:'',schema:''},xml:{message:'',schema:''}};integration=p.integration?{...integration,...p.integration}:integration;diagramKind=p.diagramKind==='flow'?'flow':'component';appSection=p.appSection==='uml'?'uml':'builder';loadIntegrationForm();tab='message';selected=root.id;showText();status('Проект открыт');}else{keep();appSection='builder';const xml=text.trim().startsWith('<');mode=xml?'xml':'json';tab=f.name.endsWith('.xsd')||(/"\$schema"/.test(text)&&!xml)?'schema':'message';texts[mode][tab]=text;showText();status('Файл открыт. Нажмите «Из текста в таблицу».');}}catch(e){status(e.message,true);}};
window.addEventListener('resize',()=>{if(appSection==='uml')renderUML();});loadIntegrationForm();showText();

